return {
  "3024 (base16)",
  "3024 (dark) (terminal.sexy)",
  "3024 Night",
  "3024 Night (Gogh)",
  "3024Night (Gogh)",
  "Aardvark Blue",
  "Abernathy",
  "Aci (Gogh)",
  "Aco (Gogh)",
  "Adventure",
  "Adventure Time (Gogh)",
  "AdventureTime",
  "Afterglow",
  "Afterglow (Gogh)",
  "Alien Blood (Gogh)",
  "AlienBlood",
  "Andromeda",
  "Apathy (base16)",
  "Apple Classic",
  "Apple System Colors",
  "Apprentice (Gogh)",
  "Apprentice (base16)",
  "Argonaut",
  "Argonaut (Gogh)",
  "Arthur",
  "Arthur (Gogh)",
  "Ashes (base16)",
  "Ashes (dark) (terminal.sexy)",
  "Astrodark (Gogh)",
  "Atelier Cave (base16)",
  "Atelier Dune (base16)",
  "Atelier Estuary (base16)",
  "Atelier Forest (base16)",
  "Atelier Heath (base16)",
  "Atelier Lakeside (base16)",
  "Atelier Plateau (base16)",
  "Atelier Savanna (base16)",
  "Atelier Seaside (base16)",
  "Atelier Sulphurpool (base16)",
  "AtelierSulphurpool",
  "Atelierdune (dark) (terminal.sexy)",
  "Atelierforest (dark) (terminal.sexy)",
  "Atelierheath (dark) (terminal.sexy)",
  "Atelierlakeside (dark) (terminal.sexy)",
  "Atelierseaside (dark) (terminal.sexy)",
  "Atlas (base16)",
  "Atom",
  "Atom (Gogh)",
  "Aura (Gogh)",
  "Aurora",
  "Ayu Dark (Gogh)",
  "Ayu Mirage",
  "Ayu Mirage (Gogh)",
  "AyuDark (Gogh)",
  "AyuMirage (Gogh)",
  "Azu (Gogh)",
  "Bamboo",
  "Bamboo Multiplex",
  "Banana Blueberry",
  "Batman",
  "Belafonte Night",
  "Belafonte Night (Gogh)",
  "BelafonteNight (Gogh)",
  "Belge (terminal.sexy)",
  "Bespin (base16)",
  "Bespin (dark) (terminal.sexy)",
  "Bim (Gogh)",
  "Birds Of Paradise (Gogh)",
  "BirdsOfParadise",
  "Bitmute (terminal.sexy)",
  "Black Metal (Bathory) (base16)",
  "Black Metal (Burzum) (base16)",
  "Black Metal (Dark Funeral) (base16)",
  "Black Metal (Gorgoroth) (base16)",
  "Black Metal (Immortal) (base16)",
  "Black Metal (Khold) (base16)",
  "Black Metal (Marduk) (base16)",
  "Black Metal (Mayhem) (base16)",
  "Black Metal (Nile) (base16)",
  "Black Metal (Venom) (base16)",
  "Black Metal (base16)",
  "Blazer",
  "Blazer (Gogh)",
  "Bleh-1 (terminal.sexy)",
  "Blue Dolphin (Gogh)",
  "Blue Matrix",
  "BlueBerryPie",
  "BlueDolphin",
  "BlulocoDark",
  "Borland",
  "Borland (Gogh)",
  "Breath (Gogh)",
  "Breath Darker (Gogh)",
  "Breath Silverfox (Gogh)",
  "BreathSilverfox (Gogh)",
  "Breeze",
  "Breeze (Gogh)",
  "Brewer (base16)",
  "Brewer (dark) (terminal.sexy)",
  "Bright (base16)",
  "Broadcast",
  "Broadcast (Gogh)",
  "Brogrammer",
  "Brogrammer (Gogh)",
  "Brogrammer (base16)",
  "Brush Trees Dark (base16)",
  "Builtin Dark",
  "Builtin Pastel Dark",
  "Builtin Solarized Dark",
  "Builtin Tango Dark",
  "Butrin (Gogh)",
  "C64",
  "C64 (Gogh)",
  "CGA",
  "Cai (Gogh)",
  "Calamity",
  "Campbell (Gogh)",
  "Canvased Pastel (terminal.sexy)",
  "Catch Me If You Can (terminal.sexy)",
  "Catppuccin Frappe",
  "Catppuccin Frappé (Gogh)",
  "Catppuccin Macchiato",
  "Catppuccin Macchiato (Gogh)",
  "Catppuccin Mocha",
  "Catppuccin Mocha (Gogh)",
  "Chalk",
  "Chalk (Gogh)",
  "Chalk (base16)",
  "Chalk (dark) (terminal.sexy)",
  "Chalkboard",
  "Chalkboard (Gogh)",
  "ChallengerDeep",
  "Chameleon (Gogh)",
  "Chester",
  "Ciapre",
  "Ciapre (Gogh)",
  "Circus (base16)",
  "City Streets (terminal.sexy)",
  "Classic Dark (base16)",
  "Clone Of Ubuntu (Gogh)",
  "CloneofUbuntu (Gogh)",
  "Cloud (terminal.sexy)",
  "Cobalt 2 (Gogh)",
  "Cobalt Neon",
  "Cobalt Neon (Gogh)",
  "Cobalt2",
  "CobaltNeon (Gogh)",
  "Codeschool (base16)",
  "Codeschool (dark) (terminal.sexy)",
  "Color Star (terminal.sexy)",
  "Colorful Colors (terminal.sexy)",
  "Colors (base16)",
  "Count Von Count (terminal.sexy)",
  "Crayon Pony Fish (Gogh)",
  "CrayonPonyFish",
  "CutiePro",
  "Cyberdyne",
  "DWM rob (terminal.sexy)",
  "DanQing (base16)",
  "Darcula (base16)",
  "Dark Ocean (terminal.sexy)",
  "Dark Pastel",
  "Dark Pastel (Gogh)",
  "Dark Violet (base16)",
  "Dark+",
  "DarkPastel (Gogh)",
  "Darkside",
  "Darkside (Gogh)",
  "Darktooth (base16)",
  "DeHydration (Gogh)",
  "Deafened (terminal.sexy)",
  "Decaf (base16)",
  "Default (dark) (terminal.sexy)",
  "Default Dark (base16)",
  "Dehydration (Gogh)",
  "Derp (terminal.sexy)",
  "Desert",
  "Desert (Gogh)",
  "Digerati (terminal.sexy)",
  "Dimmed Monokai (Gogh)",
  "DimmedMonokai",
  "Dissonance (Gogh)",
  "Django",
  "DjangoRebornAgain",
  "DjangoSmooth",
  "Doom Peacock",
  "DoomOne",
  "DotGov",
  "Dotshare (terminal.sexy)",
  "Dracula",
  "Dracula (Gogh)",
  "Dracula (Official)",
  "Dracula (base16)",
  "Dracula+",
  "Duotone Dark",
  "ENCOM",
  "Earthsong",
  "Earthsong (Gogh)",
  "Edge Dark (base16)",
  "Ef-Autumn",
  "Ef-Bio",
  "Ef-Cherie",
  "Ef-Dark",
  "Ef-Deuteranopia-Dark",
  "Ef-Dream",
  "Ef-Duo-Dark",
  "Ef-Elea-Dark",
  "Ef-Maris-Dark",
  "Ef-Melissa-Dark",
  "Ef-Night",
  "Ef-Rosa",
  "Ef-Symbiosis",
  "Ef-Trio-Dark",
  "Ef-Tritanopia-Dark",
  "Ef-Winter",
  "Eighties (base16)",
  "Eighties (dark) (terminal.sexy)",
  "Eldorado dark (terminal.sexy)",
  "Eldritch",
  "Elemental",
  "Elemental (Gogh)",
  "Elementary",
  "Elementary (Gogh)",
  "Elic (Gogh)",
  "Elio (Gogh)",
  "Embers (base16)",
  "Embers (dark) (terminal.sexy)",
  "Epiphany (terminal.sexy)",
  "Eqie6 (terminal.sexy)",
  "Equilibrium Dark (base16)",
  "Equilibrium Gray Dark (base16)",
  "Erebus (terminal.sexy)",
  "Espresso",
  "Espresso (Gogh)",
  "Espresso (base16)",
  "Espresso Libre",
  "Espresso Libre (Gogh)",
  "EspressoLibre (Gogh)",
  "Eva (base16)",
  "Eva Dim (base16)",
  "Everblush",
  "Everblush (Gogh)",
  "Everforest Dark (Gogh)",
  "Everforest Dark Hard (Gogh)",
  "Everforest Dark Medium (Gogh)",
  "Everforest Dark Soft (Gogh)",
  "EverforestDark (Gogh)",
  "Fahrenheit",
  "Fairy Floss (Gogh)",
  "Fairy Floss Dark (Gogh)",
  "FairyFloss (Gogh)",
  "FairyFlossDark (Gogh)",
  "Fairyfloss",
  "FarSide (terminal.sexy)",
  "Fideloper",
  "Firefly Traditional",
  "FirefoxDev",
  "Firewatch",
  "FishTank",
  "Fishbone (terminal.sexy)",
  "Fishtank (Gogh)",
  "Flat",
  "Flat (Gogh)",
  "Flat (base16)",
  "Flat Remix (Gogh)",
  "FlatRemix (Gogh)",
  "Flatland",
  "Flatland (Gogh)",
  "Floraverse",
  "ForestBlue",
  "Foxnightly (Gogh)",
  "Framer",
  "Framer (base16)",
  "Freya (Gogh)",
  "Frontend Fun Forrest (Gogh)",
  "Frontend Galaxy (Gogh)",
  "FrontendFunForrest (Gogh)",
  "FrontendGalaxy (Gogh)",
  "FunForrest",
  "GJM (terminal.sexy)",
  "Galaxy",
  "Galizur",
  "GeoHot (Gogh)",
  "Geohot (Gogh)",
  "Gigavolt (base16)",
  "GitHub Dark",
  "Github Dark (Gogh)",
  "Glacier",
  "Gnometerm (terminal.sexy)",
  "Gogh (Gogh)",
  "Gooey (Gogh)",
  "Google (dark) (terminal.sexy)",
  "Google Dark (Gogh)",
  "Google Dark (base16)",
  "GoogleDark (Gogh)",
  "Gotham (Gogh)",
  "Gotham (terminal.sexy)",
  "Grandshell (terminal.sexy)",
  "Grape",
  "Grape (Gogh)",
  "Grass",
  "Grass (Gogh)",
  "Grayscale (dark) (terminal.sexy)",
  "Grayscale Dark (base16)",
  "Green Screen (base16)",
  "Greenscreen (dark) (terminal.sexy)",
  "Grey-green",
  "Gruber (base16)",
  "Gruvbox Dark (Gogh)",
  "Gruvbox Material (Gogh)",
  "Gruvbox dark, hard (base16)",
  "Gruvbox dark, medium (base16)",
  "Gruvbox dark, pale (base16)",
  "Gruvbox dark, soft (base16)",
  "GruvboxDark",
  "GruvboxDarkHard",
  "Guezwhoz",
  "HaX0R_BLUE",
  "HaX0R_GR33N",
  "HaX0R_R3D",
  "Hacktober",
  "Hardcore",
  "Hardcore (Gogh)",
  "Hardcore (base16)",
  "Harmonic16 Dark (base16)",
  "Harper",
  "Harper (Gogh)",
  "Heetch Dark (base16)",
  "Helios (base16)",
  "Hemisu Dark (Gogh)",
  "HemisuDark (Gogh)",
  "Highway",
  "Highway (Gogh)",
  "Hipster Green",
  "Hipster Green (Gogh)",
  "HipsterGreen (Gogh)",
  "Hivacruz",
  "Homebrew",
  "Homebrew (Gogh)",
  "Homebrew Ocean (Gogh)",
  "Hopscotch",
  "Hopscotch (base16)",
  "Hopscotch.256",
  "Horizon Dark (Gogh)",
  "Horizon Dark (base16)",
  "HorizonDark (Gogh)",
  "Humanoid dark (base16)",
  "Hurtado",
  "Hurtado (Gogh)",
  "Hybrid",
  "Hybrid (Gogh)",
  "Hybrid (terminal.sexy)",
  "IBM3270(HighContrast) (Gogh)",
  "ICGreenPPL (Gogh)",
  "ICOrangePPL (Gogh)",
  "IC_Green_PPL",
  "IC_Orange_PPL",
  "IR Black (base16)",
  "IR_Black",
  "Ibm 3270 (High Contrast) (Gogh)",
  "Ibm3270 (Gogh)",
  "Ic Green Ppl (Gogh)",
  "Ic Orange Ppl (Gogh)",
  "Iceberg (Gogh)",
  "Icy Dark (base16)",
  "Idle Toes (Gogh)",
  "IdleToes (Gogh)",
  "Iiamblack (terminal.sexy)",
  "Insignificato (terminal.sexy)",
  "Invisibone (terminal.sexy)",
  "Ir Black (Gogh)",
  "IrBlack (Gogh)",
  "Isotope (base16)",
  "Isotope (dark) (terminal.sexy)",
  "Ivory Dark (terminal.sexy)",
  "JWR dark (terminal.sexy)",
  "Jackie Brown",
  "Jackie Brown (Gogh)",
  "JackieBrown (Gogh)",
  "Japanesque",
  "Japanesque (Gogh)",
  "Jason Wryan (terminal.sexy)",
  "Jellybeans",
  "Jellybeans (Gogh)",
  "JetBrains Darcula",
  "Kanagawa (Gogh)",
  "Kanagawa Dragon (Gogh)",
  "Kasugano (terminal.sexy)",
  "Kibble",
  "Kibble (Gogh)",
  "Kimber (base16)",
  "Kokuban (Gogh)",
  "Kolorit",
  "Konsolas",
  "Lab Fox",
  "Laser",
  "Laserwave (Gogh)",
  "Later This Evening",
  "Later This Evening (Gogh)",
  "LaterThisEvening (Gogh)",
  "Lavandula",
  "Lavandula (Gogh)",
  "Liquid Carbon (Gogh)",
  "Liquid Carbon Transparent (Gogh)",
  "LiquidCarbon",
  "LiquidCarbonTransparent",
  "LiquidCarbonTransparentInverse",
  "London Tube (base16)",
  "Londontube (dark) (terminal.sexy)",
  "Lost Woods (terminal.sexy)",
  "Low Contrast (terminal.sexy)",
  "Lumifoo (terminal.sexy)",
  "Lunaria Dark (Gogh)",
  "Lunaria Eclipse (Gogh)",
  "LunariaDark (Gogh)",
  "LunariaEclipse (Gogh)",
  "Macintosh (base16)",
  "Maia (Gogh)",
  "Mariana",
  "Marrakesh (base16)",
  "Marrakesh (dark) (terminal.sexy)",
  "Mashup Colors (terminal.sexy)",
  "Materia (base16)",
  "Material (Gogh)",
  "Material (base16)",
  "Material (terminal.sexy)",
  "Material Darker (base16)",
  "Material Palenight (base16)",
  "Material Vivid (base16)",
  "MaterialDark",
  "MaterialDarker",
  "MaterialDesignColors",
  "MaterialOcean",
  "Mathias",
  "Mathias (Gogh)",
  "Matrix (terminal.sexy)",
  "Medallion",
  "Medallion (Gogh)",
  "Mellifluous",
  "Mellow Purple (base16)",
  "Mikado (terminal.sexy)",
  "Mikazuki (terminal.sexy)",
  "Mirage",
  "Miramare (Gogh)",
  "Misterioso",
  "Misterioso (Gogh)",
  "Miu (Gogh)",
  "Mocha (base16)",
  "Mocha (dark) (terminal.sexy)",
  "Modus Vivendi (Gogh)",
  "Modus Vivendi Tinted (Gogh)",
  "Modus-Vivendi",
  "Modus-Vivendi-Deuteranopia",
  "Modus-Vivendi-Tinted",
  "Modus-Vivendi-Tritanopia",
  "Molokai",
  "Molokai (Gogh)",
  "Mona Lisa (Gogh)",
  "MonaLisa",
  "Mono (terminal.sexy)",
  "Mono Amber (Gogh)",
  "Mono Cyan (Gogh)",
  "Mono Green (Gogh)",
  "Mono Red (Gogh)",
  "Mono Theme (terminal.sexy)",
  "Mono White (Gogh)",
  "Mono Yellow (Gogh)",
  "Monokai (base16)",
  "Monokai (dark) (terminal.sexy)",
  "Monokai (terminal.sexy)",
  "Monokai Dark (Gogh)",
  "Monokai Pro (Gogh)",
  "Monokai Pro Ristretto (Gogh)",
  "Monokai Remastered",
  "Monokai Soda",
  "Monokai Soda (Gogh)",
  "Monokai Vivid",
  "MonokaiDark (Gogh)",
  "MonokaiPro (Gogh)",
  "MonokaiProRistretto (Gogh)",
  "MonokaiSoda (Gogh)",
  "Moonfly (Gogh)",
  "Morada (Gogh)",
  "Muse (terminal.sexy)",
  "N0Tch2K (Gogh)",
  "N0tch2k",
  "Nancy (terminal.sexy)",
  "Nature Suede (terminal.sexy)",
  "Navy and Ivory (terminal.sexy)",
  "Nebula (base16)",
  "Neon",
  "Neon (terminal.sexy)",
  "Neon Night (Gogh)",
  "Neopolitan",
  "Neopolitan (Gogh)",
  "Neutron",
  "Neutron (Gogh)",
  "Night Owl (Gogh)",
  "NightLion v1",
  "NightLion v2",
  "NightOwl (Gogh)",
  "Nightfly (Gogh)",
  "Nightlion V1 (Gogh)",
  "Nightlion V2 (Gogh)",
  "NightlionV1 (Gogh)",
  "NightlionV2 (Gogh)",
  "Nighty (Gogh)",
  "Nocturnal Winter",
  "Nord (Gogh)",
  "Nord (base16)",
  "Nova (base16)",
  "Nucolors (terminal.sexy)",
  "Nudge (terminal.sexy)",
  "Numix Darkest (terminal.sexy)",
  "NvimDark",
  "Obsidian",
  "Obsidian (Gogh)",
  "Ocean",
  "Ocean (base16)",
  "Ocean (dark) (terminal.sexy)",
  "Ocean Dark (Gogh)",
  "OceanDark (Gogh)",
  "Oceanic Next (Gogh)",
  "Oceanic-Next",
  "OceanicMaterial",
  "OceanicNext (Gogh)",
  "OceanicNext (base16)",
  "Ollie",
  "Ollie (Gogh)",
  "Omni (Gogh)",
  "One Dark (Gogh)",
  "One Half Black (Gogh)",
  "OneDark (Gogh)",
  "OneDark (base16)",
  "OneHalfBlack (Gogh)",
  "OneHalfDark",
  "Operator Mono Dark",
  "Orangish (terminal.sexy)",
  "Outrun Dark (base16)",
  "Overnight Slumber",
  "Oxocarbon Dark (Gogh)",
  "PaleNightHC",
  "Palenight (Gogh)",
  "Pali (Gogh)",
  "Panda (Gogh)",
  "Pandora",
  "Panels (terminal.sexy)",
  "PaperColor Dark (base16)",
  "PaperColorDark (Gogh)",
  "Papercolor Dark (Gogh)",
  "Paraiso (base16)",
  "Paraiso (dark) (terminal.sexy)",
  "Paraiso Dark",
  "Paraiso Dark (Gogh)",
  "ParaisoDark (Gogh)",
  "Parker Brothers (terminal.sexy)",
  "Pasque (base16)",
  "Pastel White (terminal.sexy)",
  "Paul Millr (Gogh)",
  "PaulMillr",
  "PaulMillr (Gogh)",
  "Pencil Dark (Gogh)",
  "PencilDark",
  "Peppermint",
  "Peppermint (Gogh)",
  "PhD (base16)",
  "Phrak1 (terminal.sexy)",
  "Pico (base16)",
  "Pixiefloss (Gogh)",
  "Pnevma",
  "Pnevma (Gogh)",
  "Poimandres",
  "Poimandres Storm",
  "Pop (base16)",
  "Popping and Locking",
  "Porple (base16)",
  "PowerShell (Gogh)",
  "Powershell (Gogh)",
  "Pretty and Pastel (terminal.sexy)",
  "Pro",
  "Pro (Gogh)",
  "Pulp (terminal.sexy)",
  "Purple People Eater (Gogh)",
  "Purple Rain",
  "PurplePeopleEater (Gogh)",
  "Purpledream (base16)",
  "Qualia (base16)",
  "Quiet (Gogh)",
  "Railscasts (base16)",
  "Railscasts (dark) (terminal.sexy)",
  "Rapture",
  "Rasi (terminal.sexy)",
  "Raycast_Dark",
  "Rebecca (base16)",
  "Red Alert",
  "Red Alert (Gogh)",
  "Red Phoenix (terminal.sexy)",
  "Red Planet",
  "Red Sands",
  "Red Sands (Gogh)",
  "RedAlert (Gogh)",
  "RedSands (Gogh)",
  "Relaxed",
  "Relaxed (Gogh)",
  "Retro",
  "Rezza (terminal.sexy)",
  "Rippedcasts",
  "Rippedcasts (Gogh)",
  "Rosé Pine (Gogh)",
  "Rosé Pine (base16)",
  "Rosé Pine Moon (Gogh)",
  "Rosé Pine Moon (base16)",
  "RoséPine (Gogh)",
  "RoséPineMoon (Gogh)",
  "Rouge 2",
  "Royal",
  "Royal (Gogh)",
  "Rydgel (terminal.sexy)",
  "Ryuuko",
  "SOS (terminal.sexy)",
  "Sakura",
  "Sandcastle (base16)",
  "Scarlet Protocol",
  "Sea Shells (Gogh)",
  "SeaShells",
  "Seafoam Pastel",
  "Seafoam Pastel (Gogh)",
  "SeafoamPastel (Gogh)",
  "Selenized Black (Gogh)",
  "Selenized Dark (Gogh)",
  "Seoul256 (Gogh)",
  "Sequoia Monochrome",
  "Seti",
  "Seti (Gogh)",
  "Seti UI (base16)",
  "Sex Colors (terminal.sexy)",
  "Shades of Purple (base16)",
  "Shaman",
  "Shaman (Gogh)",
  "Shapeshifter (dark) (terminal.sexy)",
  "Shel (Gogh)",
  "Shic (terminal.sexy)",
  "Silk Dark (base16)",
  "Simple Rainbow (terminal.sexy)",
  "Slate",
  "Slate (Gogh)",
  "SleepyHollow",
  "Smyck",
  "Smyck (Gogh)",
  "Snazzy",
  "Snazzy (Gogh)",
  "Snazzy (base16)",
  "Soft Server (Gogh)",
  "SoftServer",
  "Solar Flare (base16)",
  "Solarized (dark) (terminal.sexy)",
  "Solarized Darcula",
  "Solarized Darcula (Gogh)",
  "Solarized Dark (Gogh)",
  "Solarized Dark - Patched",
  "Solarized Dark Higher Contrast",
  "Solarized Dark Higher Contrast (Gogh)",
  "SolarizedDarcula (Gogh)",
  "SolarizedDark (Gogh)",
  "SolarizedDarkHigherContrast (Gogh)",
  "Sonokai (Gogh)",
  "SpaceGray",
  "SpaceGray Eighties",
  "SpaceGray Eighties Dull",
  "SpaceGrayEighties (Gogh)",
  "SpaceGrayEightiesDull (Gogh)",
  "Spacedust",
  "Spacedust (Gogh)",
  "Spacegray (Gogh)",
  "Spacegray Eighties (Gogh)",
  "Spacegray Eighties Dull (Gogh)",
  "Spacemacs (base16)",
  "Sparky (Gogh)",
  "Spiderman",
  "Splurge (terminal.sexy)",
  "Spring (Gogh)",
  "Square",
  "Square (Gogh)",
  "Srcery (Gogh)",
  "Sublette",
  "Subliminal",
  "Sugarplum",
  "Summer Pop (Gogh)",
  "Summerfruit Dark (base16)",
  "Sundried",
  "Sundried (Gogh)",
  "Swayr (terminal.sexy)",
  "Sweet Eliverlara (Gogh)",
  "Sweet Love (terminal.sexy)",
  "Sweet Terminal (Gogh)",
  "SweetTerminal (Gogh)",
  "Symfonic",
  "Symphonic (Gogh)",
  "Synth Midnight Terminal Dark (base16)",
  "SynthWave (Gogh)",
  "Synthwave (Gogh)",
  "Synthwave Alpha (Gogh)",
  "SynthwaveAlpha",
  "SynthwaveAlpha (Gogh)",
  "Tango (base16)",
  "Tango (terminal.sexy)",
  "Tangoesque (terminal.sexy)",
  "Tartan (terminal.sexy)",
  "Teerb",
  "Teerb (Gogh)",
  "Tender (Gogh)",
  "Terminix Dark (Gogh)",
  "TerminixDark (Gogh)",
  "Teva (terminal.sexy)",
  "Thayer Bright",
  "Thayer Bright (Gogh)",
  "ThayerBright (Gogh)",
  "The Hulk",
  "Tin (Gogh)",
  "Tinacious Design (Dark)",
  "Tokyo Night",
  "Tokyo Night (Gogh)",
  "Tokyo Night Moon",
  "Tokyo Night Storm",
  "Tokyo Night Storm (Gogh)",
  "TokyoNight (Gogh)",
  "TokyoNightStorm (Gogh)",
  "Tomorrow (dark) (terminal.sexy)",
  "Tomorrow Night",
  "Tomorrow Night (Gogh)",
  "Tomorrow Night Blue",
  "Tomorrow Night Blue (Gogh)",
  "Tomorrow Night Bright",
  "Tomorrow Night Bright (Gogh)",
  "Tomorrow Night Burns",
  "Tomorrow Night Eighties",
  "Tomorrow Night Eighties (Gogh)",
  "TomorrowNight (Gogh)",
  "TomorrowNightBlue (Gogh)",
  "TomorrowNightBright (Gogh)",
  "TomorrowNightEighties (Gogh)",
  "Toy Chest (Gogh)",
  "ToyChest",
  "Treehouse",
  "Treehouse (Gogh)",
  "Trim Yer Beard (terminal.sexy)",
  "Ubuntu",
  "UltraDark",
  "UltraViolent",
  "UnderTheSea",
  "Unikitty Dark (base16)",
  "Unikitty Reversible (base16)",
  "Unsifted Wheat (terminal.sexy)",
  "Urple",
  "Urple (Gogh)",
  "VSCodeDark+ (Gogh)",
  "VWbug (terminal.sexy)",
  "Vacuous 2 (terminal.sexy)",
  "Vag (Gogh)",
  "Vaughn",
  "Vaughn (Gogh)",
  "Vesper",
  "Vibrant Ink (Gogh)",
  "VibrantInk",
  "Vice Alt (base16)",
  "Vice Dark (base16)",
  "Violet Dark",
  "VisiBlue (terminal.sexy)",
  "VisiBone (terminal.sexy)",
  "Visibone Alt. 2 (terminal.sexy)",
  "Vs Code Dark+ (Gogh)",
  "Warm Neon (Gogh)",
  "WarmNeon",
  "Website (Gogh)",
  "Wez",
  "Wez (Gogh)",
  "Whimsy",
  "Wild Cherry (Gogh)",
  "WildCherry",
  "Windows 10 (base16)",
  "Windows 95 (base16)",
  "Windows High Contrast (base16)",
  "Windows NT (base16)",
  "Wombat",
  "Wombat (Gogh)",
  "Woodland (base16)",
  "Wryan",
  "Wryan (Gogh)",
  "Wzoreck (Gogh)",
  "X::DotShare (terminal.sexy)",
  "X::Erosion (terminal.sexy)",
  "XCode Dusk (base16)",
  "Zenburn",
  "Zenburn (Gogh)",
  "Zenburn (base16)",
  "arcoiris",
  "astromouse (terminal.sexy)",
  "ayu",
  "carbonfox",
  "catppuccin-frappe",
  "catppuccin-macchiato",
  "catppuccin-mocha",
  "cyberpunk",
  "darkermatrix",
  "darkmatrix",
  "darkmoss (base16)",
  "deep",
  "duckbones",
  "duskfox",
  "farmhouse-dark",
  "flexoki-dark",
  "gooey (Gogh)",
  "gotham (Gogh)",
  "hardhacker",
  "hund (terminal.sexy)",
  "iTerm2 Dark Background",
  "iTerm2 Default",
  "iTerm2 Pastel Dark Background",
  "iTerm2 Smoooooth",
  "iTerm2 Solarized Dark",
  "iTerm2 Tango Dark",
  "ibm3270 (Gogh)",
  "iceberg-dark",
  "idea",
  "idleToes",
  "jmbi (terminal.sexy)",
  "jubi",
  "kanagawa (Gogh)",
  "kanagawabones",
  "kokuban (Gogh)",
  "kurokula",
  "laserwave (Gogh)",
  "lovelace",
  "matrix",
  "midnight-in-mojave",
  "mono-amber (Gogh)",
  "mono-cyan (Gogh)",
  "mono-green (Gogh)",
  "mono-red (Gogh)",
  "mono-white (Gogh)",
  "mono-yellow (Gogh)",
  "neobones_dark",
  "neon-night (Gogh)",
  "nightfox",
  "nighty (Gogh)",
  "niji",
  "nord",
  "nordfox",
  "palenight (Gogh)",
  "pinky (base16)",
  "purplepeter",
  "rebecca",
  "rose-pine",
  "rose-pine-moon",
  "s3r0 modified (terminal.sexy)",
  "seoulbones_dark",
  "shades-of-purple",
  "summer-pop (Gogh)",
  "summercamp (base16)",
  "sweet-eliverlara (Gogh)",
  "synthwave",
  "synthwave-everything",
  "tender (base16)",
  "terafox",
  "theme2 (terminal.sexy)",
  "thwump (terminal.sexy)",
  "tlh (terminal.sexy)",
  "tokyonight",
  "tokyonight-storm",
  "tokyonight_moon",
  "tokyonight_night",
  "tokyonight_storm",
  "vulcan (base16)",
  "wilmersdorf",
  "zenbones_dark",
  "zenburn (terminal.sexy)",
  "zenburned",
  "zenwritten_dark",
}
